import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Orline from '@/components/Orline'
import Button from '@/components/Button'

export default function Home() {
  return (
    <>
      <Head>
        <title>X. It's what's happening/X</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo/twitterlogo.ico" />
      </Head>
      <main className={styles.container}>
        <div className={styles.logoSection}>
        <Image src="/Images/twitterlogo.png" alt="Twitter Logo" width={450} height={350}
        />
        <div className={styles.loginSection}>
        <h1 className={styles.title}>Happening now</h1>
        <h2 className={styles.subtitle}>Join today.</h2>
        <div>
        <Button
        text="Sign up with Google" logo="/Images/googlelogo.png" className={styles.button}/>
        <br />
        <Button text="Sign up with Apple" logo="/Images/applelogo.png" className={styles.button}/>
        </div>
        <div>
          <Orline />
        <Button text="Create account" className={styles.createAccountButton} style={{color: "white", background: "#1DA1F2"}}/>
          <br />
          
          <div style={{color: "rgb(113, 118, 123)", width: "300px;"}}>
              <span>By signing up, you agree to the </span>
              <a href="https://twitter.com/tos" ><span >Terms of Service</span></a> 
              <span> and </span> 
              <a href="https://twitter.com/privacy"><span >Privacy Policy</span></a>
              <span>, including </span> 
              <a href="https://help.twitter.com/rules-and-policies/twitter-cookies" ><span >Cookie Use.</span></a>
          </div>

          <h3 className={styles.subtitle2}>Already have an account?</h3>
          <Button text="Sign in" className={styles.createSignInButton} style={{color: "#1DA1F2", background: "white"}}/>
          </div>
        </div>
        </div>
      </main>


      <nav aria-label="Footer" >

<a href="https://about.twitter.com" style={{color: "rgb(113, 118, 123)"}}>
<span>About</span></a>
<span> </span>
<a href="https://help.twitter.com/using-x/download-the-x-app" style={{color: "rgb(113, 118, 123)"}}>
<span>Download the X app</span></a>
<span> </span>
<a href="https://help.twitter.com" style={{color: "rgb(113, 118, 123)"}}>
<span>Help Center</span></a>
<span> </span>
<a href="https://twitter.com/tos" style={{color: "rgb(113, 118, 123)"}}>
<span>Terms of Service</span></a>
<span> </span>
<a href="https://twitter.com/privacy" style={{color: "rgb(113, 118, 123)"}}>
<span>Privacy Policy</span></a>
<span> </span>
<a href="https://support.twitter.com/articles/20170514" style={{color: "rgb(113, 118, 123)"}}>
<span>Cookie Policy</span></a>
<span> </span>
<a href="https://help.twitter.com/resources/accessibility" style={{color: "rgb(113, 118, 123)"}}>
<span>Accessibility</span></a>
<span> </span>
<a href="https://business.twitter.com/en/help/troubleshooting/how-twitter-ads-work.html?ref=web-twc-ao-gbl-adsinfo&amp;utm_source=twc&amp;utm_medium=web&amp;utm_campaign=ao&amp;utm_content=adsinfo" style={{color: "rgb(113, 118, 123)"}}>
<span>Ads info</span></a>
<span> </span>
<a href="https://blog.twitter.com" style={{color: "rgb(113, 118, 123)"}}><span >Blog</span></a><a href="https://status.twitterstat.us" style={{color: "rgb(113, 118, 123)"}}>
<span>Status</span></a>
<span> </span>
<a href="https://careers.twitter.com" style={{color: "rgb(113, 118, 123)"}}><span >Careers</span></a><a href="https://about.twitter.com/press/brand-assets" style={{color: "rgb(113, 118, 123)"}}>
<span>Brand Resources</span></a>
<span> </span>
<a href="https://ads.twitter.com/?ref=gl-tw-tw-twitter-advertise" style={{color: "rgb(113, 118, 123)"}}><span >Advertising</span></a><a href="https://marketing.twitter.com" style={{color: "rgb(113, 118, 123)"}}>
<span>Marketing</span></a>
<span> </span>
<a href="https://business.twitter.com/?ref=web-twc-ao-gbl-twitterforbusiness&amp;utm_source=twc&amp;utm_medium=web&amp;utm_campaign=ao&amp;utm_content=twitterforbusiness" style={{color: "rgb(113, 118, 123)"}}>
<span>X for Business</span></a>
<span> </span>
<a href="https://developer.twitter.com" style={{color: "rgb(113, 118, 123)"}}>
<span>Developers</span></a>
<span> </span>
<a href="https://twitter.com/i/directory/profiles" style={{color: "rgb(113, 118, 123)"}}><span >Directory</span></a>
<span> </span>
<a href="/settings" style={{color: "rgb(113, 118, 123)"}}>
<span>Settings</span></a>
<span> </span>
<div style={{color: "rgb(113, 118, 123)"}}>
<span>© 2024 X Corp.</span></div>

</nav>


    </>
  )
}
