import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Orline from '@/components/Orline'
import Button from '@/components/Button'
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>X. It's what's happening/X</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo/twitterlogo.ico" />
      </Head>
      <main className={styles.container}>
        <div className={styles.logoSection}>
        <Image src="/Images/twitterlogo.png" alt="Twitter Logo" width={450} height={350}
        />
        <div className={styles.loginSection}>
        <h1 className={styles.title}>Happening now</h1>
        <h2 className={styles.subtitle}>Join today.</h2>
        <div>
        <Button
        text="Sign up with Google" logo="/Images/googlelogo.png" className={styles.button}/>
        <br />
        <Button text="Sign up with Apple" logo="/Images/applelogo.png" className={styles.button}/>
        </div>
        <div>
          <Orline />
        <Button text="Create account" className={styles.createAccountButton} style={{color: "white", background: "#1DA1F2"}}/>
          <br />
          
          <div style={{color: "rgb(113, 118, 123)", width: "300px;"}}>
              <span>By signing up, you agree to the </span>
              <a href="https://twitter.com/tos" ><span >Terms of Service</span></a> 
              <span> and </span> 
              <a href="https://twitter.com/privacy"><span >Privacy Policy</span></a>
              <span>, including </span> 
              <a href="https://help.twitter.com/rules-and-policies/twitter-cookies" ><span >Cookie Use.</span></a>
          </div>

          <h3 className={styles.subtitle2}>Already have an account?</h3>
          <Button text="Sign in" className={styles.createSignInButton} style={{color: "#1DA1F2", background: "white"}}/>
          </div>
        </div>
        </div>
      </main>
      <Footer />

    </>
  )
}
